function [spectrum_region_of_interest] = select_frequencies_OI(spectrum, brain_region_OI, electrode_labels, list_of_electrodes_wanted)

% Selecting electrodes of interest for each participant, and return matrix
% where averaged over those electrodes

% Define structure:
spectrum_region_of_interest = [];

% Define electrodes of brain region of interest that we want
switch brain_region_OI
    case 'frontal'
        electrodes_OI = {'Z1', 'Z2', 'Z3', 'Z4', 'Z5',...
                      'R1', 'R2', 'R3', 'R4', 'R5', 'R6',...
                      'RR1', 'RR2', 'RR3','RR4', 'RR5',...
                      'RD1', 'RD2', 'RD3',...
                      'RC1', 'RC2', 'RC3',...
                      'RB1', 'RB2',...
                      'RA1', 'RA2',...
                      'RE1',...
                      'L1', 'L2', 'L3', 'L4', 'L5', 'L6',...
                      'LL1', 'LL2', 'LL3', 'LL4', 'LL5',...
                      'LD1', 'LD2', 'LD3',...
                      'LC1', 'LC2', 'LC3',...
                      'LB1', 'LB2', ...
                      'LA1', 'LA2',...
                      'LE1'};
    case 'parietal'
        electrodes_OI =  {'Z6', 'LL6', 'RR6', 'R7', 'L7', 'RR7', 'LL7', 'LA3', 'RA3', 'LA4', 'RA4', 'R8', 'L8'};
    case 'occipital'
        electrodes_OI =  {'Z10', 'Z11', 'Z12', 'Z13', 'Z14',...
                        'R11', 'R12', 'R13', 'R14',...
                        'L11', 'L12', 'L13', 'L14',...
                        'LL11', 'LL12', 'LL13',...
                        'RR11', 'RR12', 'RR13', ...
                        'RE4', 'LE4'};
    case 'temporal'
        electrodes_OI = {'RB3', 'RB4', 'RB5', 'RB6',...
                       'RC4', 'RC5', 'RC6', 'RC7',...
                       'RD4', 'RD5', 'RD6', 'RD7',...
                       'RE2', 'RE3', 'Rm',...
                       'LB3', 'LB4', 'LB5', 'LB6',...
                       'LC4', 'LC5', 'LC6', 'LC7', ...
                       'LD4', 'LD5', 'LD6', 'LD7',...
                       'LE2', 'LE3', 'Lm'};
    case 'central'
        electrodes_OI =  {'Z8', 'LL8', 'RR8', 'LA5', 'RA5', 'L9', 'R9', 'Z9', 'LL9', 'RR9', 'L10', 'R10', 'RR10', 'LL10'};
    case 'specific'
        % Give specific electrodes and not average over entire brain region
        % (may cancel out effects...)
        electrodes_OI = list_of_electrodes_wanted;
    otherwise 
        error('Region not defined');
end

num_electrodes = length(electrode_labels);
count_electrode = 1;

% Loop over every electrode
for current_electrode_index = 1:num_electrodes
    
    if ismember(electrode_labels{current_electrode_index}, electrodes_OI)
        % We have an electrode that we are interested in: retrieving data
        % for final structure
        
        spectrum_region_of_interest(count_electrode,:,:) = spectrum(current_electrode_index,:,:);
        
        count_electrode = count_electrode + 1;
    end
    
end


end

